#
# autogenerated by ./script/generate-required-contexts, do not modify
#
variable "required_contexts" {
  type = map(list(string))
  default = {
    "octodns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)"],
    "octodns-azure" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-cloudflare" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-constellix" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ddns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-digitalocean" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dnsimple" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dnsmadeeasy" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dyn" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "setup-py"],
    "octodns-easydns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-edgedns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-etchosts" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-gandi" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-gcore" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-googlecloud" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-hetzner" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-mythicbeasts" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ns1" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ovh" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "setup-py"],
    "octodns-powerdns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-rackspace" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-route53" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-selectel" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-template" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-transip" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ultra" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
  }
}
