#
# autogenerated by ./script/generate-required-contexts, do not modify
#
variable "required_contexts" {
  type = map(list(string))
  default = {
    "octodns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "ci (octodns/octodns-azure)", "ci (octodns/octodns-cloudflare)", "ci (octodns/octodns-constellix)", "ci (octodns/octodns-ddns)", "ci (octodns/octodns-digitalocean)", "ci (octodns/octodns-dnsimple)", "ci (octodns/octodns-dnsmadeeasy)", "ci (octodns/octodns-dyn)", "ci (octodns/octodns-easydns)", "ci (octodns/octodns-edgedns)", "ci (octodns/octodns-etchosts)", "ci (octodns/octodns-gandi)", "ci (octodns/octodns-gcore)", "ci (octodns/octodns-googlecloud)", "ci (octodns/octodns-hetzner)", "ci (octodns/octodns-mythicbeasts)", "ci (octodns/octodns-ns1)", "ci (octodns/octodns-ovh)", "ci (octodns/octodns-powerdns)", "ci (octodns/octodns-rackspace)", "ci (octodns/octodns-route53)", "ci (octodns/octodns-selectel)", "ci (octodns/octodns-transip)", "ci (octodns/octodns-ultra)"],
    "octodns-azure" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-cloudflare" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-constellix" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ddns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-digitalocean" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dnsimple" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dnsmadeeasy" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-dyn" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "setup-py"],
    "octodns-easydns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-edgedns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-etchosts" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-gandi" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-gcore" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-googlecloud" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-hetzner" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-mythicbeasts" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ns1" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ovh" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "setup-py"],
    "octodns-powerdns" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-rackspace" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-route53" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-selectel" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-template" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-transip" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
    "octodns-ultra" = ["ci (3.7)", "ci (3.8)", "ci (3.9)", "ci (3.10)", "setup-py"],
  }
}
