#!/bin/bash
# Usage: script/bootstrap
# Ensures all dependencies are installed locally.

set -e

cd "$(dirname "$0")"/..
ROOT=$(pwd)

echo "This repo assumes you have tfenv installed, if not 'brew install tfenv' should get it going assumning you use Homebrew"

tfenv install `cat .terraform-version`
terraform init

if [ ! -e .env ]; then
  cat <<EOF
It is suggested that you create a .env file and define the following in it

# this access token will need full repo and org scope for the octodns org
export GITHUB_TOKEN="<access-token>"
export GITHUB_OWNER="octodns"

and then source .env before running terraform.
EOF
fi
