#!/usr/bin/env python3

from yaml import safe_load
from sys import argv
from urllib import request
from urllib.error import HTTPError

try:
    branch = argv[1]
except IndexError:
    branch = 'main'

with open('repos.tf') as fh:
    lines = fh.read().split('\n')

for i, line in enumerate(lines):
    if '"repos" {' in line:
        break

repos = ['octodns']
for i in range(i+3, len(lines)):
    line = lines[i]
    if '}' in line:
        break
    repo = line[5:].split('"', 1)[0]
    repos.append(repo)

lines = [
    '#',
    f'# autogenerated by ./script/generate-required-contexts, do not modify',
    '#',
    'variable "required_contexts" {',
    '  type = map(list(string))',
    '  default = {',
]

def get_jobs(data):
    jobs = data['jobs']
    matrix = jobs['ci']['strategy']['matrix']
    key = list(matrix.keys())[0]
    others = []
    if 'setup-py' in jobs:
        others.append('setup-py')
    return [f'ci ({v})' for v in matrix[key]] + others

for repo in repos:
    print(f'loading {repo}')
    url = f'https://github.com/octodns/{repo}/raw/{branch}/' \
        '.github/workflows/main.yml'
    try:
        fh = request.urlopen(url)
    except HTTPError as e:
        if e.code == 404:
            continue
        raise

    data = safe_load(fh.read())
    jobs = get_jobs(data)

    jobs = '", "'.join(jobs)
    lines.append(f'    "{repo}" = ["{jobs}"],')

lines.extend([
    '  }',
    '}',
])

print(f'writing required-contexts.tf')
with open('required-contexts.tf', 'w') as fh:
    fh.write('\n'.join(lines))
    fh.write('\n')
